version: '3.8'

services:
  # FoodXchange Backend Application - Development Mode
  foodxchange-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: foodxchange-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9090:9090"  # Metrics port
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=0.0.0.0
      - MONGODB_URI=mongodb://mongo:27017/foodxchange
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=foodxchange-super-secret-jwt-key-that-is-at-least-32-characters-long-for-development
      - JWT_REFRESH_SECRET=foodxchange-refresh-token-secret-that-is-at-least-32-characters-long-for-development
      - LOG_LEVEL=debug
      - METRICS_ENABLED=true
      - HEALTH_CHECK_ENABLED=true
      - PERFORMANCE_MONITORING_ENABLED=true
      - FEATURE_CACHING=true
      - FEATURE_RATE_LIMITING=false  # Disabled for development
      - FEATURE_ANALYTICS=true
      - DEV_ENABLE_DEBUG_ROUTES=true
      - DEV_ENABLE_PROFILING=true
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - foodxchange-network
    command: sh -c "npm install && npm run dev"

  # MongoDB Database (Latest 7.0.x)
  mongo:
    image: mongo:7.0.5
    container_name: foodxchange-mongo-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db
      - mongo-config-dev:/data/configdb
    networks:
      - foodxchange-network

  # Redis Cache (Latest 7.2.x Alpine)
  redis:
    image: redis:7.2.4-alpine
    container_name: foodxchange-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data-dev:/data
    networks:
      - foodxchange-network
    command: redis-server --appendonly yes

volumes:
  mongo-data-dev:
    driver: local
  mongo-config-dev:
    driver: local
  redis-data-dev:
    driver: local

networks:
  foodxchange-network:
    driver: bridge